language: node_js
node_js:
  - "16"
services:
  - docker

before_install:
  - npm install

script:
  - npm run build
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t reuspect/dockertest:latest .
  - docker push reuspect/dockertest:latest

